sudo: required
dist: trusty
addons:
   apt:
      sources:
         - google-chrome
      packages:
         - google-chrome-stable
         # latest version of firefox already installed by default
language: node_js
node_js:
   - "6"
before_install:
   - npm config set spin false
install:
   - npm install -g webdriver-manager
   - webdriver-manager update
   - npm install
script:
   - npm run test
   - npm run test-protractor